server:
  port: 9999

spring:
  application:
    name: gateway-app
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE

